{% set name = "pdm-backend" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdm_backend-{{ version }}.tar.gz
  sha256: b853cb049244b697f5ebe9028d34418449130d6e12adf71b7661a4b95c342d59

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - importlib-metadata >=3.6  # [py<310]
  run:
    - python
    - importlib-metadata >=3.6  # [py<310]

test:
  imports:
    - pdm.backend
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pdm-backend/
  summary: The build backend used by PDM that supports latest packaging standards.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - theAeon
    - xhochy
