{% set name = "pdm-backend" %}
{% set version = "2.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdm_backend-{{ version }}.tar.gz
  sha256: dbd9047a7ac10d11a5227e97163b617ad5d665050476ff63867d971758200728

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    # "pdm-backend" bootstraps itself using its own code, so we need to have the runtime dependencies at build time
    - importlib-metadata >=3.6  # [py<310]
  run:
    - python
    - importlib-metadata >=3.6  # [py<310]

test:
  imports:
    - pdm.backend
  source_files:
    - tests/
  requires:
    - {{ compiler('c') }}  # [linux or win]
    - editables
    - pip
    - pytest
    - pytest-xdist
  commands:
    - pip check
    - pytest tests -vv

about:
  home: https://pdm-backend.fming.dev/
  summary: The build backend used by PDM that supports latest packaging standards.
  description: |
    The build backend used by PDM that supports latest packaging standards.
    This is the backend for PDM projects that is fully-compatible with PEP 517 spec, 
    but you can also use it alone. It reads the metadata of PEP 621 format and coverts it to Core metadata.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/pdm-project/pdm-backend
  doc_url: https://pdm-backend.fming.dev/

extra:
  recipe-maintainers:
    - theAeon
    - xhochy
